version: '3.9'

services:
  next:
    container_name: next
    image: cedo/next
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      # if you are using reverse proxy you dont need to expose the port
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # you dont need to expose the port, use it if you want to connect to databse from your local machine while developing
    ports:
      - "5432:5432"
volumes:
  postgres_data: