version: '3.9'

services:
  next:
    container_name: next
    image: cedo/next
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3001:3000"
  db:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
